### ISSUE TITLE
"Slight" issue with memory leaking

### ISSUE THREAD

**Issue by the2048** [jariz/Akku#104]
Given two or three disconnects of my JVC headphones from my laptop (a T430s with 8 GB of RAM running Catalina), Akku occasionally rises to unhealthy levels of memory use; I have seen up to 30GB reported, however at the time of this issue being made, it was only around 1.8 to 2GB of RAM used. 

What could be causing this? 
![image](https://user-images.githubusercontent.com/37256486/121274321-80160900-c887-11eb-920c-435ddd0a8bae.png)

**Comment by jariz** [comment]
It's probably related to #42. Best to just leave the 'show notification at...' setting at never for now until that bug is fixed.

**Comment by jariz** [comment]
also, duplicate (#100), so closing in favour of that one
