### ISSUE TITLE
when I click the 'settings' , nothing happened

### ISSUE THREAD

**Issue by aaron2wh** [jariz/Akku#107]

**Comment by Mavyre** [comment]
Got the same issue

**Comment by Robert-ale** [comment]
I have the same issue, the program is installed on a Mac Mini M1.

**Comment by jariz** [comment]
Settings should not be clickable. It's supposed to be a header.
I've indeed seen some cases where the settings header becomes clickable when the UI gets updated while the menu is opened, but just click the icon again in that case, not really something I would consider all that blocking.

'Show notification at...' and 'Start with system' are the only settings the app has.
