### ISSUE TITLE
TL;DR: Appreciation

### ISSUE THREAD

**Issue by mavenor** [jariz/Akku#109]
The title of this ticket is self-explanatory 😂
And it isn't just me who needs to thank @jariz, but it's also my WH-1000XM3, whose battery is definitely in a far better condition with shallower discharges, thanks to its status always being visible in Akku.
So thanks! Love the work you've done here!
And I'm sure I speak for tons of others (and their Bluetooth devices' Li-ion packs) too!

**Comment by mavenor** [comment]
And when it came to the little bugs, like the notification spamming (#42), I must say that if it's ever possible for a bug to grow on you, some of Akku's *did* grow on me. Thanks to the said bug, I never let my headset drop below 20% (out of fear-of-being-spammed 😂), and we all know that [shallow discharges do less harm than deep ones](https://batteryuniversity.com/article/bu-808-how-to-prolong-lithium-based-batteries).

**Comment by mavenor** [comment]
**Update:** After years of not supporting their own specification (see [README.md](https://github.com/jariz/Akku#readme), Apple finally introduced support in macOS Monterey.
I doubt they'll introduce any updates to the prior versions, including Big Sur, so Akku will still be relevant to a ton of people

**Comment by jariz** [comment]
@EccentricHyphus37 thanks!
Did not knew that about Monterey, about time!
I'm really hoping I can get a dev environment going during my time off soon, and fix some of the more pressing bugs, this is still one of my favorite projects I've ever done, just so little time...
