### ISSUE TITLE
Not working with Anker Soundbuds Curve

### ISSUE THREAD

**Issue by escobar5** [jariz/Akku#110]
Battery levels appear on Android, but Akku is showing "No reported battery state (yet)"

**Comment by mzahidriaz-tr** [comment]
@escobar5 it's working fine for me on Big Sur 11.4
I have to disconnect and reconnect bluetooth.

**Comment by mzahidriaz-tr** [comment]
Apologies: it's showing status of battery, but it's not updating it. to get updated battery status, I've disconnect and reconnect again.

**Comment by escobar5** [comment]
it's working now, I have tried reconnecting several times and it wasn't working, but now it does.
