### ISSUE TITLE
Error on Mac OS Monterrey

### ISSUE THREAD

**Issue by santiaguf** [jariz/Akku#121]
When I open Akku, i get this error: 
_**The operation couldn’t be completed. (io_jari_AkkuHelper.BluetoothHCIError error 5.)**_
<img width="263" alt="Screen Shot 2021-10-25 at 4 31 03 PM" src="https://user-images.githubusercontent.com/810823/138774005-b21f3c27-7828-4427-81bc-b2805ef44adc.png">

This error is on Mac OS Monterrey 12.0.1

**Comment by natuan62** [comment]
I have same error

**Comment by jariz** [comment]
Monterey can read battery state by itself. 
https://piunikaweb.com/2021/06/14/macos-monterey-shows-battery-percentage-for-3rd-party-bt-audio-devices/

Akku is effectively deprecated there, so I have currently no plans to add support.

**Comment by santiaguf** [comment]
@jariz that's true. 
<img width="321" alt="Screen Shot 2021-10-27 at 8 47 15 AM" src="https://user-images.githubusercontent.com/810823/139079140-5c1e1035-1bb8-4ca4-8964-16e3dfc7e5e7.png">
Thanks for creating Akku, it was very useful for me.
