### ISSUE TITLE
Display AirPod battery state (+ other system-approved devices)

### ISSUE THREAD

**Issue by jariz** [jariz/Akku#18]
The system does recognise the battery state of AirPods, for consistency sake it'd be nice if Akku would display these too.
Akku _should_ be able to use the normal IOBluetooth API's to do this (airpods do not appear to communicate through AT commands)

**Comment by thamaraiselvam** [comment]
I have been using Bluetooth keyboard and mouse(Not apple products) it would be if it shows those devices battery as well.
