### ISSUE TITLE
Sparkle doesn't recognize currently installed version correctly

### ISSUE THREAD

**Issue by jariz** [jariz/Akku#24]
![](https://jari.lol/7ef12wUY7D.png)

Also heroku app is reallllyyy slow. Maybe just switch to something else.

**Comment by Toxblh** [comment]
Try to look counter bundle - I catch the same problem then to do manipulate with the number manually.

**Comment by jariz** [comment]
Fixed in a9df080f78a8f7f749124448595c47168e43ee5b
