### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by othoma** [jariz/Akku#25]
Hello, 
Akku seems to be what I'm looking for. 
It might be a silly question but how do I actually install this on my computer ?

Thanks for answering.

**Comment by jariz** [comment]
Hi! Cool that you're interested in the project! (considering I haven't promoted it at all so far)

I'm currently working out some of the kinks in the updating system and will release a stable version somewhere this month, but if you're eager to give it a try (and don't mind the auto update not working) you can head on over to the [releases page](https://github.com/jariz/Akku/releases) and grab one of the pre-release versions.

**Comment by luckyycode** [comment]
O hey man, I would like to use it too!

**Comment by othoma** [comment]
I don't understand how come I didn't see this. 

Hartelijk dank.
