### ISSUE TITLE
Out of bounds: index >= endIndex (EventPacket.init, L2CapPacket.init, etc)

### ISSUE THREAD

**Issue by othoma** [jariz/Akku#26]
My headset is well recognised by Akku, yet the battery level isn't displayed. 
Even though it is on iOS. 

If I can help with Wireshark, I'll be glad to do so

<img width="1280" alt="screenshot 2019-01-03 at 16 34 19" src="https://user-images.githubusercontent.com/31987678/50646227-dd4e5780-0f75-11e9-8bd7-e8a1d0349e62.png">

![img_1314](https://user-images.githubusercontent.com/31987678/50646387-33bb9600-0f76-11e9-8671-d7880faae5ce.png)

**Comment by jariz** [comment]
Ah, that sucks.
Have you tried restarting the app and reconnecting a couple times?

If that doesn't help,, a packet log in this case would be very useful indeed.
I'm still working on a bit more formal process for filing these types of issues, but here's a quick run down:

- Restart your Mac (kind of important, else audio data might be restored from your log)
- Connect your device
- Go to `Terminal` and execute:
```
sudo /System/Library/Frameworks/IOBluetooth.framework/Versions/A/Resources/BluetoothReporter --dumpPacketLog /var/log/upload_me.pklg && open --reveal /var/log/upload_me.pklg
```
- Enter your password, upload the file that appears in finder to somewhere and attach it here.

**Comment by othoma** [comment]
Holy F***, you're quick. I like that.

I restarted right before posting. Disconnect / connect doesn't seem to have an impact.

Here is the file as pklg files seem not to be supported in GitHub.
[pklg log file](https://we.tl/t-0y46AdawUv)

**Comment by jariz** [comment]
Haha, kinda excited I have someone testing this out 😀

Hmmm I'm seeing a lot of data being send but no connections being made, did you run the command immediately after connecting?
Also, to prevent other devices from muddling the traffic, ensure only the headset is connected.

Considering you mentioned wireshark, if it's not too much trouble, before uploading it again, open the file with wireshark and enter `btrfcomm.address` in the 'Apply a display filter' field (& hit enter), if it doesn't show any results, it means wireshark can't find any useful data (and neither will I)
If it does, please upload it again.

**Comment by othoma** [comment]
I was listening to music when I ran the command in the first place.

Here's what i did: turned my iPhone's bluetooth off, restart the macbook (with headset off), turned headset on (which connected automatically) to macbook, ran the command, filtered it to wireshark. As it shows some data, I upload the new generated file (hoping there will be less data and will be easier to analyse)

[file](https://we.tl/t-wxbtTkIUIx)

**Comment by jariz** [comment]
Definitely some useful stuff in there, thanks!
One final thing I forgot to ask, can you upload the AkkuHelper log located at `/Library/Logs/AkkuHelper.log`?

**Comment by othoma** [comment]
Great then, 

All I have is [Akku.log](https://github.com/jariz/Akku/files/2724752/Akku.log) which was located in ~/Library/logs and not /Library/Logs/AkkuHelper.log

Is it what you need ?

**Comment by jariz** [comment]
Hm. That's weird. Seems like the helper app is crashing immediately.
But errors should automatically be reported and I'm not getting any. 
That combined with the fact that there's no log file at all makes this kind of hard to debug.
OK, final question (and apologies for the amount of questions :P ), are there any `/Library/Logs/DiagnosticReports/io.jari.AkkuHelper_*.crash` files?

**Comment by othoma** [comment]
No need to apologise.
I really appreciate your help. I have indeed several of them.
Again they're not supported, so I'll use wetransfer. Not really convenient for long term file housing, but...

https://we.tl/t-fufNfmMHZC

**Comment by jariz** [comment]
No problem, got all the files downloaded now.
Alright great, these are super useful!

Weird the reports didn't get send to me automatically, but nevertheless.
Going to attempt to make a fix sometime this week, thanks for your quick replies!

**Comment by othoma** [comment]
I was behind an enterprise proxy all day long, could be the reason why?

**Comment by jariz** [comment]
Could be the reason yea!

**Comment by jariz** [comment]
@othoma Just released a version that should fix this, can you give it a try?

**Comment by othoma** [comment]
@jariz It definitely works!!! 
Thanks
