### ISSUE TITLE
App isn't working on Catalina beta

### ISSUE THREAD

**Issue by tomtastic** [jariz/Akku#35]
Not that I expect anything to work in a beta release of a new OS, but FYI :

<img width="449" alt="Screenshot 2019-08-29 at 15 16 33" src="https://user-images.githubusercontent.com/302127/63949452-54d77680-ca72-11e9-8429-5304473a20a5.png">

MacOS Catalina : beta 19A546d

```
29-08-2019 15:27:49 ERROR alertWithError():108 - The operation couldn’t be completed. (io_jari_AkkuHelper.BluetoothHCIError error 0.)
```
https://pastebin.com/bm3qiizz

**Comment by jariz** [comment]
Interesting. I'm hoping they didn't remove any of the obscure API's that Akku uses.
I don't really wanna upgrade my personal computer because I can't risk it breaking, but can you upload the following file for me?:
`/System/Library/Frameworks/IOBluetooth.framework/Versions/Current/Resources/BluetoothReporter`
(if it even still exists 🤞)

**Comment by tomtastic** [comment]
The output or the file itself?

**Comment by jariz** [comment]
The file itself. I reverse engineered it to build akku 😂

**Comment by tomtastic** [comment]
https://we.tl/t-VYkgmiKxIq

**Comment by jariz** [comment]
Biggest change seems to be that they renamed the IOService from IOBluetoothHCIController to IOBluetoothPacketlogger. Everything else seems largely the same? So making it work on Catalina should be trivial.

![](https://jari.lol/4qGkG8dqTW.png)

Will get to it when I upgrade my own mac.
If you're feeling adventurous, you can try changing the name in the Akku source and see what happens.

https://github.com/jariz/Akku/blob/0bcda7d961abdec3e7a7cb7edca0f2e6968b3b07/AkkuHelper/Bluetooth/Driver.swift#L32

**Comment by tomtastic** [comment]
$ brew install ruby node.js cocoapods
Edit /usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod to use "#!/usr/bin/env ruby"
$ npm install --save nan
$ gem install xcpretty
$ mkdir build && ./build
<img width="319" alt="Screenshot 2019-09-01 at 16 16 44" src="https://user-images.githubusercontent.com/302127/64078596-894a6d00-ccd4-11e9-9780-fd2135ff60f5.png">

**Comment by tomtastic** [comment]
Bleh, code signing issues.
I can't find any combination of personal (I have no paid Apple Developer account) code signing identity that works sadly.

**Comment by jariz** [comment]
There's a script in the repo that should set the correct info in the plists. 
Haven't really documented this yet.

First run a build:
```
./build.sh
```
Then:

```
./Scripts/SMJobBlessUtil.py setreq build/Build/Products/Release/Akku.app Akku/Info.plist AkkuHelper/Helper-Info.plist
```

And rebuild.

Could you try that real quick?
If that doesn't work, we'll just wait for the release of Catalina.

**Comment by tomtastic** [comment]
Ahha, thanks for the tip, new error sadly :
```
The operation couldn’t be completed. (io_jari_AkkuHelper.BluetoothHCIError error 5.)
```

**Comment by jariz** [comment]
Looks like this error:

https://github.com/jariz/Akku/blob/0bcda7d961abdec3e7a7cb7edca0f2e6968b3b07/AkkuHelper/Enums/BluetoothHCIError.swift#L25-L26

Which is a bit harder to fix and is gonna take some more reverse engineering.
Thanks for your time 😛

**Comment by tomtastic** [comment]
Thanks, let me know if I can send you anything else, I'd be more than happy to help.

**Comment by svkostrov** [comment]
Pleeeease update this super app for Catalina =)

**Comment by jariz** [comment]
Not sure why it didn't work for @tomtastic earlier, but just made the same changes I suggested in this thread and it worked fine. New release soon.

**Comment by jorgemartins** [comment]
hello, sorry for replying to a closed issue, but didn't want to open a new one as it is the same issue.
I tried to build the version after your latest commit c7c2550 but, when running the app and click install the helper, i'm getting a :
`Failed to install helper with error: Error Domain=CFErrorDomainLaunchd Code=4 "(null)"`

I've noticed that tomtastic also had this error and said that it was related to signing, but when I try your suggestion  https://github.com/jariz/Akku/issues/35#issuecomment-527088672 and run that command it says :
`build/Build/Products/Release/Akku.app: app designated requirement malformed`

(I've also did apply the sign to run locally option in xcode)
![Screenshot 2019-12-16 at 11 35 50](https://user-images.githubusercontent.com/1323193/70904037-48166880-1ff8-11ea-9f94-772c181df76f.png)
![Screenshot 2019-12-16 at 11 35 44](https://user-images.githubusercontent.com/1323193/70904038-48aeff00-1ff8-11ea-80d7-4bb2fcf07778.png)

Wonder if you submit a release it solves it, or am I doing something wrong? 😓 

thanks 🙏

**Comment by joacovidal** [comment]
Hi all! I'm facing the same issue here.

@jariz Would you be so kind to upload an updated build? Last one is from august, and is missing this fix.

Thank you so much for your work

**Comment by jariz** [comment]
Hi @joacovidal @jorgemartins et. al, thanks for your patience, I should've released a update way earlier but got cocky and decided I wanted to include more bugfixes, which I eventually did not have time for.

Nevertheless, a new version should be out now, thanks for your patience.
