### ISSUE TITLE
Very Unstable Connection After Installing

### ISSUE THREAD

**Issue by kerti** [jariz/Akku#41]
Hi,

I have a pair of SoundPeats Truengine SE True Wireless Earphones. I've installed Akku and it seems to work displaying the battery percentage. Unfortunately, the connection seems to go crazy. The earphones would seem to connect and disconnect multiple times per second. It seemed like the app was fighting for control with some other app.

I'd be happy to provide you more information so that you can resolve the issue, but for now is there any way I can completely uninstall Akku along with its companion app? I mean the one requiring root password, which intercepts BT communications.

Thanks a lot!

**Comment by jariz** [comment]
Haven't seen this before. Apologies!
If you could give me more information (see here what information: https://github.com/jariz/Akku/blob/master/CONTRIBUTING.md), that would be much appreciated.

The helper app should not be running if Akku itself is not running. 
If it somehow still is (or just want to make sure it can't anymore), you can remove it manually by hitting 'cmd+shift+g' in finder, entering `/Library/PrivilegedHelperTools` in the dialog, hitting enter, and deleting the` io.jari.AkkuHelper` file.

**Comment by jariz** [comment]
And, other than the companion app, the app itself can be uninstalled like any other app, just drag it to trash.

**Comment by kerti** [comment]
Hi @jariz,

First of all, please don't apologize. I downloaded a beta pre-release, so I know what I was getting into. In fact, I really appreciate what you're doing, including your swift response.

So here's what happened:

* I've installed Akku while my earphones were still connected. When Akku requested permission for the companion app, I gave it.
* I tried uninstalling Akku by dragging it to the trash, and then reinstalling it. The issue persisted at this moment.
* The connection went crazy like I mentioned before, and I opened this issue.
* I used Bluetooth Explorer to force my earphones to switch to AptX. It was previously using AAC. This seemed to work. If I switch back to AAC, it'll go crazy again.
* The following morning (20 minutes ago, I'm at GMT+7), I tried deleting the companion app, without realizing that Akku was still installed. I switched to AAC and it seemed to work.
* I tried to reinstall Akku, at which point I realized that it is still installed and Catalina asked if I wanted to replace the existing installation. I answered yes.
* I ran Akku once more, giving it permission to install the companion app, **this time with my earphones disconnected**.
* I reconnected my earphones and everything worked!

I think the key takeaway here is the fact that I needed to install Akku while my earphones were disconnected.

If you still need the packet dump and logs, do let me know and I'll send them over. Maybe you can experiment with replicating the issue on your end, and if you need me to try to replicate the issue also please let me know and I'd be happy to help.

**Comment by jariz** [comment]
Thanks for the kind words, @kerti
