### ISSUE TITLE
Can't start the app

### ISSUE THREAD

**Issue by armanto** [jariz/Akku#44]
Akku version:  Release 0.1.0-beta.11
Download page: https://github.com/jariz/Akku/releases/tag/0.1.0-beta.11

OS: 10.15.3 (19D76)
MacBook Pro (16-inch, 2019)
Processor 2.6 GHz 6-Core Intel Core i7
Memory 16 GB 2667 MHz DDR4

Got this message when open up the app:

“Akku” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

**Comment by jariz** [comment]
I'm on the same version. Did you go to security/privacy settings to allow it to run? Catalina has stricter permissions requiring an additional approval.
I'm going to get it notarized on the next release which should prevent this from happening.

**Comment by KuroiRoy** [comment]
You can go to the application in the Applications folder and right click, then click open in the context menu. Doing it this way Mac will ask if you trust the app instead of blocking it outright

**Comment by armanto** [comment]
Yes yes.. I can run it now. Thanks! Sorry for the late response
