### ISSUE TITLE
Building it myself ended in errors.

### ISSUE THREAD

**Issue by SoPat712** [jariz/Akku#70]
![2020-08-07_13-05-52](https://user-images.githubusercontent.com/30350506/89670288-f2f0d500-d8ae-11ea-9023-f10a0ee64106.png)
errors occur when trying to run pod install, which is needed to get sentry for the project

Developer app signing also led to an error

`No signing certificate "Developer ID Application" found`

Any help is appreciated.

**Comment by jariz** [comment]
Hi sourav, 
Did you run ./build.sh ?
The development setup is a bit of a pain right now. My first  next step for this project is either greatly simplifying it or at least documenting it.

**Comment by SoPat712** [comment]
I did not run ./build.sh. I'll try that ASAP.

**Comment by SoPat712** [comment]
Running ./build.sh did indeed fix the problem. Now I'm having issues with seeing the apps menu bar icon. The app is shown to be running, but the akku helper app is not prompting me for an admin password, and I'm not sure what's really happening. I'm working on that myself, and I'm closing this issue for now.
