### ISSUE TITLE
Cannot install the .dmg file

### ISSUE THREAD

**Issue by ronssij** [jariz/Akku#71]
![image](https://user-images.githubusercontent.com/24932380/89838204-3d1ed280-db9d-11ea-80ea-5ea40b755f07.png)

**Comment by SoPat712** [comment]
Step by Step Solution.

Step 1: Open System Preferences.

Step 2: Open Security and Privacy

Step 3: Click on General in the top 4 sections

Step 4: Below "Allow Apps Downloaded From", you should see a popup saying allow.

Step 5: Click the Lock icon in the bottom left

Step 6: Enter your password

Step 7: Click a now clickable `allow` button next to the system prompt

**Comment by jariz** [comment]
Thanks @SoPat712, this should indeed "fix" it.
Next version will be notarized to prevent this error.
@ronssij I will close this issue now, feel free to reopen if you're still finding problems.

**Comment by ronssij** [comment]
Im still having issues with the helper thingy.

**Comment by ronssij** [comment]
It fixed the problem, stop it from running on the activity monitor. delete the application the re-install it.
