### ISSUE TITLE
it says the app needs update

### ISSUE THREAD

**Issue by Jjaaack** [jariz/Akku#74]
<img width="764" alt="Screen Shot 2020-09-02 at 11 18 24 AM" src="https://user-images.githubusercontent.com/70660152/92021075-08221d80-ed0e-11ea-81bb-d09c6d0c99be.png">

**Comment by jariz** [comment]
Please see the response to #71

**Comment by Jjaaack** [comment]
@jariz Thank you sooooooo much!!!!!!

**Comment by Jjaaack** [comment]
it worked!!!!!!

**Comment by jariz** [comment]
Glad to hear that 😀
