### ISSUE TITLE
One Plus Bullet Battery info missing.

### ISSUE THREAD

**Issue by kamleshkarwande** [jariz/Akku#76]
Akku is able to detect the connected One Plus bullet wireless headphone. But its not showing any battery information.

**Comment by SoPat712** [comment]
Hi, if you're unable to see the battery info, please follow this [guide](https://github.com/jariz/Akku/blob/master/CONTRIBUTING.md#my-device-does-not-work). Development has mostly stopped on this repo as the main developer is working on other projects, but you're welcome to try and fork the repo yourself and try your own hand at Swift development?
