### ISSUE TITLE
Not working with EDIFIER TWS1

### ISSUE THREAD

**Issue by markvivv** [jariz/Akku#77]
I just see the message "No reported battery state (yet), try reconnecting."
I have tried restarting the app and reconnecting the device. Is there anything else I can try or do to troubleshoot the issue?
I'm willing to help add support for the device if I can.

I have successfully captured the btrfcomm.address packet as requested, please take a look!
<img width="1667" alt="QQ20200925-180004@2x" src="https://user-images.githubusercontent.com/447704/94254190-00dee000-ff59-11ea-9db6-31ea89cfecdb.png">
[upload_me.pklg.zip](https://github.com/jariz/Akku/files/5281998/upload_me.pklg.zip)
[AkkuHelper.log](https://github.com/jariz/Akku/files/5281995/AkkuHelper.log)
[Akku.log](https://github.com/jariz/Akku/files/5281996/Akku.log)

**Comment by kaiofreitas** [comment]
Same here with the EDIFIER W830BT
