### ISSUE TITLE
Statusbar

### ISSUE THREAD

**Issue by elalemanyo** [jariz/Akku#78]
How can I access the battery to show it in the statusbar? I use [better touch app](https://folivora.ai)

Thanks for this nice app!

**Comment by jariz** [comment]
HI, see the discussion on #59

**Comment by jariz** [comment]
Considering you're the second person to ask this, it would be appreciated if you wrote down the exact instructions needed to get it to work with better touch app so I could document it.

**Comment by elalemanyo** [comment]
With better touch app you can run for example a shell, javascript oder AppleScript and get some information. What is the best way to get the battery information from the headset? Why is this so complicated? I start playing with blueutil but battery level is not possible. I also try with `ioreg` and read that on linux would be possible with `upower`... why is this so complicated?
I am testing all of this with a MacBook and Sony WH-1000XM3.

Thanks

**Comment by jariz** [comment]
Nothing on MacOS will read the battery state of a headset. Currently Akku is the only app to be able to do this.
You will have to run the AkkuHelper with the `--standalone` flag and parse it's output.
Not gonna be super simple I'm afraid.

**Comment by elalemanyo** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3856862/95327989-2ea31d80-08a5-11eb-845a-9cae8beae244.png">
But where is the battery level?

**Comment by jariz** [comment]
Try reconnecting, it will only read the current buffer of bluetooth communication, so if you played any audio etc the battery information will be gone from the buffer.
Like mentioned in the discussion, you will have to run this command every minute or so.
