### ISSUE TITLE
Stuck in greyed out "Install my helper app"

### ISSUE THREAD

**Issue by sunilvaltix** [jariz/Akku#81]
So, I clicked on the "Install my helper app" and its just sitting there and apparently not doing anything.

I have couple of questions:

1. Why can't this helper be part of the app itself?
2. Is it bundled separately at github? Where is the source code for the helper app?

**Comment by merlin-zaraza** [comment]
Yep, the same for me. Killing app and helper and started it again resolved this issue.

**Comment by SpyGuy0215** [comment]
> Yep, the same for me. Killing app and helper and started it again resolved this issue.

Yes, that's what worked for me as well!

**Comment by deanc** [comment]
Can confirm here also that I had this experience on install. Killing and restarting worked.
