### ISSUE TITLE
Battery level Notification At Wrong Level

### ISSUE THREAD

**Issue by SpyGuy0215** [jariz/Akku#86]
I was using Akku, when, it started spamming the Low Battery notification. It says that my headset (Powerbeats2 Wireless) only has 20% left. However, both Akku and the Beats Updater say it has a full 100%. So, it won't stop spamming me with notifications! Please fix this ASAP.

**Comment by SpyGuy0215** [comment]
OH GEEZ HELP!!! Even when my headphones aren't connected, Akku is spamming me with low battery messages!! I got on my computer this morning and found that I had 1345 notifs! From Akku! Plz fix ASAP

Edit: Restarted Akku and it fixed the above issue, but for all I know it could come back again

**Comment by jariz** [comment]
Duplicate #42, also, this application is 

- free
- clearly marked as experimental
- made by one guy
- did I say free?

So please mind your manners a bit.

**Comment by jariz** [comment]
You can work around this in the meantime for now by simply disabling the notification setting.
