### ISSUE TITLE
install my helper app gets grey and gets stuck

### ISSUE THREAD

**Issue by Johnnn213** [jariz/Akku#90]
here is the message that the terminal gives me after i insert the passcode to enable the helper app:

**2021-01-21 22:04:16.544 Akku[2192:538119] Sentry Started -- Version: 4.1.0
22:04:23 ❤️ ERROR - Helper connection was closed with error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named io.jari.AkkuHelper was invalidated from this process." UserInfo={NSDebugDescription=The connection to service named io.jari.AkkuHelper was invalidated from this process.}**

**Comment by karacaalp** [comment]
i faced same type "top" to terminal. Then find pid of akku on list. then kill app with that `kill pid`.

Then restart the application it will solve the problem

**Comment by etekweb** [comment]
You can also use Activity Monitor to "force quit" the Akku app. (For me the PID for Akku didn't show up as one of the top CPU usage processes.) Restarting after that worked for me.
