### ISSUE TITLE
No way to cleanly uninstall

### ISSUE THREAD

**Issue by rdamazio** [jariz/Akku#94]
I tried this app, it unfortunately didn't work with my headset (B&W PX7), so I decided to uninstall it. However, there's no way to automatically remove the helper.

These are the scattered files I managed to find:
/Library/PrivilegedHelperTools/io.jari.AkkuHelper
/Library/LaunchDaemons/io.jari.AkkuHelper.plist
Not sure if there are any others I missed.

In addition, I had to manually remove the login item.

**Comment by Yann-R** [comment]
Hi,
A free app like [AppCleaner](https://freemacsoft.net/appcleaner/) detects both your files, and two more things:
- /Library/PrivilegedHelperTools/io.jari.AkkuHelper
- /Library/LaunchDaemons/io.jari.AkkuHelper.plist
- ~/Library/Cache/Akku
- ~/Library/Logs/Akku.log

Hope that's all...

**Comment by maosmurf** [comment]
> Hi,
> A free app like [AppCleaner](https://freemacsoft.net/appcleaner/) detects both your files, and two more things:
> 
>     * /Library/PrivilegedHelperTools/io.jari.AkkuHelper
> 
>     * /Library/LaunchDaemons/io.jari.AkkuHelper.plist
> 
>     * ~/Library/Cache/Akku
> 
>     * ~/Library/Logs/Akku.log
> 
> 
> Hope that's all...

In addition to your list, my AppCleaner also found

* ~/Library/Preferences/io.jari.Akku.plist
<img width="896" alt="Screenshot 2021-07-07 at 10 34 40" src="https://user-images.githubusercontent.com/193583/124727817-5811d800-df0f-11eb-903e-1aed35d82841.png">
