### ISSUE TITLE
App doesn't work with Galaxy Buds Plus

### ISSUE THREAD

**Issue by manrodric** [jariz/Akku#95]
Hi, I installed the app correctly today but I only can see this:

<img width="459" alt="Screen Shot 2021-03-01 at 22 11 20" src="https://user-images.githubusercontent.com/9144261/109591228-2a3d0280-7adb-11eb-960a-11e76f56c0a4.png">

Thank you.

**Comment by dep** [comment]
Galaxy Buds Pro as well.  Works with my Wyze Headphones though.

![image](https://user-images.githubusercontent.com/55112925/134199207-057b32e0-c3d3-4671-8767-f1a17c87471b.png)

**Comment by dep** [comment]
@jariz  does this mean it's fixed?

**Comment by dep** [comment]
Oh now I see https://github.com/jariz/Akku/issues/122 - take care

**Comment by jariz** [comment]
yes, apologies, wanted to clean up the issues, but can't easily place a comment on them all.
