### ISSUE TITLE
Akku” can’t be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by ImtiazEpu** [jariz/Akku#98]
This software needs to be updated. Contact the developer for more information.

![Screenshot at Apr 05 13-50-28](https://user-images.githubusercontent.com/27789950/113551087-ed9e8280-9615-11eb-8a00-934b8eee1c21.png)

MacOS Catalina. Version 10.15.7

**Comment by etekweb** [comment]
You can bypass this by right-clicking on the Akku app file, then clicking Open.

**Comment by ImtiazEpu** [comment]
@etekweb It's not working. Same issue.

**Comment by jariz** [comment]
Go to security and privacy in system settings > click 'open anyway'
