### ISSUE TITLE
Lag in Battery Percentage

### ISSUE THREAD

**Issue by UjjwalGupta-Git** [jariz/Akku#99]
Here to report a bug. I installed this app. It works fine and all but when it comes to 60% or lower it kinda glitches from 60 to 50 and vice versa rapidly. Tell me if you want more info.

**Comment by UjjwalGupta-Git** [comment]
Right now it's glitching between 100% and 190%

**Comment by timgws** [comment]
Do you have any further information? What version of macOS are you running? What device are you trying to find battery information for?
